- name: variable at task level
  hosts: localhost
  vars: 
  - money: "100000rs"
    land: "10hectars"
  tasks:
  - name: inherit value from play
    ansible.builtin.debug:
     msg: "MONEY: {{money}},LAND: {{land}}"
  - name: inherit values from play and add values
    vars:
    - money: "200000rs"
      houses: "3 houses"
    ansible.builtin.debug:
      msg: "MONEY: {{money}},LAND:{{land}},HOUSES:{{houses}}"